[workspace]
authors = ["cadenpage <ckp634@my.utexas.edu>"]
channels = ["conda-forge"]
name = "rotom"
platforms = ["linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
tqdm = ">=4.67.3,<5"
pygame = ">=2.6.1,<3"

[pypi-dependencies]
feetech-servo-sdk = ">=1.0.0, <2"
